/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 356549263ad4fbac0dd004e5ad101ffc)
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 02d6ed2e71ee5d9468a560deb09aad4c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore";
	}
	interface Env {
		DesignAIStore: KVNamespace;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		SEND_EMAIL: SendEmail;
		AI: Ai;
		IMAGES: ImagesBinding;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;

		// OAuth and Security (Runtime secrets)
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		JWT_SECRET: string;
		CSRF_SECRET: string;
		ENABLE_EMAIL_REGISTRATION: string;
		SECRETS_ENCRYPTION_KEY: string;

		// AI Gateway & LLV Providers
		CLOUDFLARE_AI_GATEWAY_URL: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		OPENROUTER_API_KEY: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		SERPAPI_KEY: string;

		// Sentry & Observability
		SENTRY_DSN: string;
		ENVIRONMENT: string;

		// Cloudflare API & Access
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		CF_ACCESS_ID: string;
		CF_ACCESS_SECRET: string;

		// GitHub Exporter
		GITHUB_EXPORTER_CLIENT_ID: string;
		GITHUB_EXPORTER_CLIENT_SECRET: string;

		// Sandbox & Deployment
		SANDBOX_SERVICE_TYPE: string;
		SANDBOX_SERVICE_URL: string;
		SANDBOX_SERVICE_API_KEY: string;
		ALLOCATION_STRATEGY: string;
		USE_TUNNEL_FOR_PREVIEW: boolean;
		CUSTOM_PREVIEW_DOMAIN: string;

		// Bindings
		DISPATCHER: any;

		TEMPLATES_REPOSITORY: "https://github.com/Digital-platoon/designai-templates";
		ALLOWED_EMAIL: "anyone can use it";
		DISPATCH_NAMESPACE: "designai-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "designai-gateway";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		CUSTOM_DOMAIN: "designai.dev";
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "anyone can use it";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		CUSTOM_DOMAIN: "designai.dev";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "CUSTOM_DOMAIN">> { }
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "CUSTOM_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE">> {}
}
