/**
 * Supplemental type declarations for runtime secrets and env vars
 * that are NOT generated by `wrangler types` (i.e. set via `wrangler secret`
 * or `.dev.vars`).
 *
 * The generated `worker-configuration.d.ts` already declares
 * `Cloudflare.Env` with the bindings from `wrangler.jsonc`.
 * TypeScript merges both declarations automatically.
 */
declare namespace Cloudflare {
    interface Env {
        // --- Auth & Secrets (runtime secrets) ---
        JWT_SECRET?: string;
        CSRF_SECRET?: string;
        SECRETS_ENCRYPTION_KEY?: string;
        ENABLE_EMAIL_REGISTRATION?: string;

        // --- OAuth Providers (runtime secrets) ---
        GOOGLE_CLIENT_ID?: string;
        GOOGLE_CLIENT_SECRET?: string;
        GITHUB_CLIENT_ID?: string;
        GITHUB_CLIENT_SECRET?: string;
        GITHUB_EXPORTER_CLIENT_ID?: string;
        GITHUB_EXPORTER_CLIENT_SECRET?: string;

        // --- AI Provider Keys (runtime secrets) ---
        OPENROUTER_API_KEY?: string;
        GOOGLE_AI_STUDIO_API_KEY?: string;
        ANTHROPIC_API_KEY?: string;
        OPENAI_API_KEY?: string;
        SERPAPI_KEY?: string;

        // --- Cloudflare API & Account (runtime secrets) ---
        CLOUDFLARE_API_TOKEN?: string;
        CLOUDFLARE_ACCOUNT_ID?: string;
        CLOUDFLARE_AI_GATEWAY_URL?: string;
        CLOUDFLARE_AI_GATEWAY_TOKEN?: string;

        // --- Sentry & Observability ---
        SENTRY_DSN?: string;
        CF_ACCESS_ID?: string;
        CF_ACCESS_SECRET?: string;
        ENVIRONMENT?: string;

        // --- Email ---
        SEND_EMAIL?: SendEmail;
        RESEND_API_KEY?: string;

        // --- Sandbox & Services ---
        SANDBOX_SERVICE_TYPE?: string;
        SANDBOX_SERVICE_URL?: string;
        SANDBOX_SERVICE_API_KEY?: string;
        ALLOCATION_STRATEGY?: string;
        USE_TUNNEL_FOR_PREVIEW?: string;
        CUSTOM_PREVIEW_DOMAIN?: string;
    }
}
